### ISSUE TITLE
Worked with offline?

### ISSUE THREAD

**Issue by Caserol23** [EFHIII/midi-ch#3]
I've been downloaded the source and pasted it to my XAMPP, its not working when its offline, but its arrived the download when it goes internet and pops-up the download prompt?

But the code runs smoothly, no download prompt on offline, it has prompt when goes internet.

**Comment by EFHIII** [comment]
I'm not sure what you're trying to do, some more context would be helpful, but If what you're doing is trying to run the files in this repo without internet, then the problem's that that this makes use of a few libraries as well as bootstrap, so without internet, those libraries can't be downloaded.
