### ISSUE TITLE
Code license

### ISSUE THREAD

**Issue by mtolly** [EFHIII/midi-ch#5]
Heya, I'm writing to ask if your code here is available under a free/open-source software license -- I was interested in building off of it but could not find a license designation.

For context, I develop an app that supports converting charts between various game formats such as CH/RB/GH. I would like to add a few different pieces of functionality that depend on a decent way to "shrink" note charts into a smaller number of lanes like your tool does, such as making a 5-fret guitar chart from formats like:

* RB Pro Guitar
* RB Pro Keys
* Vocals
* 6-fret guitar
* Rocksmith
* BeatMania

I made a quick demo to try out a few of these with your logic and the results are very promising!

If allowed to integrate your work, I would of course:

* credit you in release notes + app readme + copyright file
* credit you in comments/metadata on any output files that use the logic (such as `loading_phrase` in `song.ini` like your app does)

**Comment by EFHIII** [comment]
I added a license. If you have any questions about the algorithm, feel free to ask. You can also get quicker responses from me via [Discord](https://discord.gg/CuXJx8vJ2y). Also let me know if you end up making anything cool, I'd love to see it.
